
# model
num_time_bins: 512
num_space_bins: 1024
d_model: 768
num_heads: 8
num_layers: 12
num_map_tokens: 16
max_seq_len: 600
num_channels: 6
device: cuda:1

# training 
num_epochs: 100
batch_size: 16
eval_freq: 10
use_wandb: True
save_freq: 1000
save_path: /nfs/kun2/users/cglossop/gcs_saved_models

# dataset
time_max: 0.5
time_min: 0
space_max: 1
space_min: -1
env_shape: [6,6]
train_data_folder: /mnt/gcs_transformer/data/data_split/train/train_files.txt
val_data_folder: /mnt/gcs_transformer/data/data_split/val/val_files.txt
test_data_folder: /mnt/gcs_transformer/data/data_split/test/test_files.txt
